local Config = {
    Teams = {
        {
            Id = "planicie",
            DisplayName = "Time Planicie",
            BiomeId = "planicie",
            BiomeDisplayName = "Planicie",
            Color = Color3.fromRGB(119, 201, 105),
            BasePosition = Vector3.new(0, 0, -260),
        },
        {
            Id = "selva",
            DisplayName = "Time Selva",
            BiomeId = "selva",
            BiomeDisplayName = "Selva",
            Color = Color3.fromRGB(47, 175, 84),
            BasePosition = Vector3.new(0, 0, 260),
        },
        {
            Id = "deserto",
            DisplayName = "Time Deserto",
            BiomeId = "deserto",
            BiomeDisplayName = "Deserto",
            Color = Color3.fromRGB(239, 191, 102),
            BasePosition = Vector3.new(251, 0, -145),
        },
        {
            Id = "taiga",
            DisplayName = "Time Taiga",
            BiomeId = "taiga",
            BiomeDisplayName = "Taiga",
            Color = Color3.fromRGB(77, 138, 156),
            BasePosition = Vector3.new(251, 0, 145),
        },
        {
            Id = "neve",
            DisplayName = "Time Neve",
            BiomeId = "neve",
            BiomeDisplayName = "Neve",
            Color = Color3.fromRGB(196, 229, 242),
            BasePosition = Vector3.new(-251, 0, 145),
        },
        {
            Id = "cogumelos",
            DisplayName = "Time Cogumelos",
            BiomeId = "cogumelos",
            BiomeDisplayName = "Cogumelos",
            Color = Color3.fromRGB(193, 81, 109),
            BasePosition = Vector3.new(-251, 0, -145),
        },
    },

    Biomes = {
        planicie = {
            Id = "planicie",
            DisplayName = "Planicie",
            FloorColor = Color3.fromRGB(110, 176, 79),
            AccentColor = Color3.fromRGB(187, 232, 153),
            DetailMaterial = Enum.Material.Grass,
        },
        deserto = {
            Id = "deserto",
            DisplayName = "Deserto",
            FloorColor = Color3.fromRGB(217, 191, 114),
            AccentColor = Color3.fromRGB(250, 222, 154),
            DetailMaterial = Enum.Material.Sand,
        },
        taiga = {
            Id = "taiga",
            DisplayName = "Taiga",
            FloorColor = Color3.fromRGB(86, 128, 130),
            AccentColor = Color3.fromRGB(132, 174, 176),
            DetailMaterial = Enum.Material.Slate,
        },
        selva = {
            Id = "selva",
            DisplayName = "Selva",
            FloorColor = Color3.fromRGB(44, 142, 60),
            AccentColor = Color3.fromRGB(93, 204, 116),
            DetailMaterial = Enum.Material.Grass,
        },
        neve = {
            Id = "neve",
            DisplayName = "Neve",
            FloorColor = Color3.fromRGB(216, 234, 240),
            AccentColor = Color3.fromRGB(255, 255, 255),
            DetailMaterial = Enum.Material.Snow,
        },
        cogumelos = {
            Id = "cogumelos",
            DisplayName = "Cogumelos",
            FloorColor = Color3.fromRGB(110, 66, 96),
            AccentColor = Color3.fromRGB(208, 108, 132),
            DetailMaterial = Enum.Material.Mud,
        },
    },

    Match = {
        MaxPlayers = 12,
        MinPlayersToStart = 2,
        MinTeamsToStart = 2,
        SupportedTeamCounts = { 2, 3, 4, 5, 6 },
        PreferredPlayersPerTeam = 2,
        AllowPartialTeams = false,
        PlayersPerTeam = 2,
        CountdownSeconds = 8,
        RespawnSeconds = 5,
        SuddenDeathSeconds = 12 * 60,
        PostMatchSeconds = 12,
        MaxCoreHealth = 4,
        CoreDamagePerHit = 1,
        SpectatorHeight = 46,
        JoinMidMatchPolicy = "LobbyUntilNextRound",
        Formats = {
            Solo1v1 = {
                Mode = "Solo1v1",
                MinPlayers = 2,
                MaxPlayers = 3,
                TeamCount = 2,
                PlayersPerTeam = 1,
                PlayerLimit = 2,
                DisplayName = "1v1",
            },
            Duos = {
                Mode = "Duos",
                MinPlayers = 4,
                MaxPlayers = 12,
                MinTeams = 2,
                MaxTeams = 6,
                PlayersPerTeam = 2,
                DisplayNameSingular = "dupla",
                DisplayNamePlural = "duplas",
            },
        },
    },

    World = {
        Lobby = {
            SpawnPosition = Vector3.new(0, 4, 442),
            PlatformSize = Vector3.new(150, 4, 120),
            WalkwaySize = Vector3.new(34, 2, 124),
            ViewDeckSize = Vector3.new(52, 2, 32),
            SafeZoneHalfExtents = Vector3.new(76, 18, 62),
        },
        Spectator = {
            DeckPosition = Vector3.new(0, 26, 0),
            DeckSize = Vector3.new(42, 2, 42),
        },
    },

    Generators = {
        MaxPickupsPerGenerator = 5,
        ResourceDefinitions = {
            Iron = {
                Color = Color3.fromRGB(212, 219, 224),
                Material = Enum.Material.Metal,
                PickupSize = Vector3.new(2.4, 1.2, 2.4),
            },
            Gold = {
                Color = Color3.fromRGB(245, 205, 48),
                Material = Enum.Material.Neon,
                PickupSize = Vector3.new(2.2, 1, 2.2),
            },
            Emerald = {
                Color = Color3.fromRGB(23, 226, 154),
                Material = Enum.Material.Neon,
                PickupSize = Vector3.new(2.4, 1.4, 2.4),
            },
        },
        GeneratorTypes = {
            BaseIron = {
                ResourceType = "Iron",
                SpawnInterval = 1.6,
                Amount = 4,
                TeamScoped = false,
            },
            BaseGold = {
                ResourceType = "Gold",
                SpawnInterval = 4.2,
                Amount = 1,
                TeamScoped = false,
            },
            MidEmerald = {
                ResourceType = "Emerald",
                SpawnInterval = 7.2,
                Amount = 1,
                TeamScoped = false,
            },
        },
        ForgeIntervals = {
            1.0,
            0.82,
            0.66,
        },
        PickupCollectionDistance = 10,
    },

    Interaction = {
        ShopDistance = 18,
        UpgradeDistance = 18,
    },

    Shop = {
        Items = {
            {
                Id = "wool_bundle",
                DisplayName = "La x20",
                Category = "Blocos",
                ResourceType = "Iron",
                Cost = 12,
                GrantType = "BlockTool",
                Charges = 20,
            },
            {
                Id = "stone_sword",
                DisplayName = "Espada de Pedra",
                Category = "Combate",
                ResourceType = "Gold",
                Cost = 6,
                GrantType = "SwordTool",
                DamageBonus = 10,
            },
            {
                Id = "iron_pickaxe",
                DisplayName = "Picareta de Ferro",
                Category = "Ferramentas",
                ResourceType = "Gold",
                Cost = 4,
                GrantType = "PickaxeTool",
            },
            {
                Id = "healing_potion",
                DisplayName = "Pocao de Vida",
                Category = "Suporte",
                ResourceType = "Emerald",
                Cost = 4,
                GrantType = "HealTool",
                HealAmount = 40,
            },
        },
    },

    TeamUpgrades = {
        Items = {
            {
                Id = "sharpness",
                DisplayName = "Afiacao",
                TierCosts = { 4 },
                ResourceType = "Emerald",
                EffectType = "SwordBonus",
                EffectValues = { 6 },
            },
            {
                Id = "protection",
                DisplayName = "Protecao",
                TierCosts = { 4, 8 },
                ResourceType = "Emerald",
                EffectType = "DamageReduction",
                EffectValues = { 0.12, 0.22 },
            },
            {
                Id = "forge",
                DisplayName = "Forja",
                TierCosts = { 8, 12 },
                ResourceType = "Emerald",
                EffectType = "ForgeTier",
                EffectValues = { 2, 3 },
            },
        },
    },

    Combat = {
        SwordBaseDamage = 24,
        SwordHitRange = 11,
        SwordHitAngleDot = 0.3,
        SwordCooldownSeconds = 0.55,
        PickaxeHitRange = 12,
        PickaxeCooldownSeconds = 0.6,
        BlockPlacementDistance = 10,
        BlockGrid = 4,
        BlockHealth = 1,
        KillCreditWindowSeconds = 8,
        SpawnProtectionSeconds = 2,
        RestrictedPlacementRadius = 9,
    },

    UI = {
        Title = "CS Fan Zone Arena",
        QueueText = "Aguardando jogadores",
        MatchStateLabels = {
            Waiting = "Aguardando",
            Starting = "Contagem",
            Active = "Partida",
            SuddenDeath = "Morte Subita",
            Ended = "Encerrada",
        },
        ResourceLabels = {
            Iron = "Ferro",
            Gold = "Ouro",
            Emerald = "Esmeralda",
        },
        GuidedSteps = {
            {
                Id = "collect_iron",
                Title = "Pegue Ferro",
                Hint = "Encoste no gerador cinza e junte ferro rapido.",
                Target = "Gerador de Ferro",
            },
            {
                Id = "open_shop",
                Title = "Abra a Loja",
                Hint = "Vire para a loja azul e abra o menu.",
                Target = "Loja",
            },
            {
                Id = "buy_blocks",
                Title = "Compre Blocos",
                Hint = "Compre La x20 e prepare a primeira saida.",
                Target = "La x20",
            },
            {
                Id = "build_bridge",
                Title = "Construa ate a Ilha do Meio",
                Hint = "Use os blocos na saida amarela da base.",
                Target = "Saida para a Ilha do Meio",
            },
            {
                Id = "collect_emerald",
                Title = "Pegue Esmeralda",
                Hint = "Va para o Meio e pegue o drop verde.",
                Target = "Esmeralda",
            },
            {
                Id = "attack_or_defend",
                Title = "Defenda ou ataque o Totem",
                Hint = "Fortaleça a base ou compre picareta para pressionar.",
                Target = "Totem",
            },
        },
        StarterFlow = {
            First = "wool_bundle",
            Second = "stone_sword",
            Third = "iron_pickaxe",
        },
        ObjectiveIcons = {
            Iron = "[Fe]",
            Gold = "[Au]",
            Emerald = "[Es]",
            Totem = "[T]",
            Middle = "[M]",
            Center = "[C]",
            Shop = "[$]",
        },
        KidHelpMessages = {
            Lobby = "Olhe a arena e memorize a rota Base -> Meio -> Centro.",
            Starting = "Voce vai nascer numa base. Primeiro: ferro, depois loja.",
            FirstBridge = "Ponte pronta. Continue ate a Ilha do Meio.",
            FirstEmerald = "Boa. Esmeralda agora vira upgrade ou picareta.",
            TotemDown = "Seu totem caiu. A proxima morte elimina.",
            Spectating = "Sem respawn. Veja quem ainda protege o totem.",
        },
        Onboarding = {
            Title = "Como vencer",
            Objectives = {
                "Proteja seu totem",
                "Colete ferro, ouro e esmeralda",
                "Compre blocos e equipamentos",
                "Destrua o totem inimigo para vencer a rodada",
            },
            StartingText = "Voce vai para uma base. Ao nascer: pegue ferro e abra a loja.",
            ByPhase = {
                Lobby = {
                    "Olhe o centro e leia as saidas da arena",
                    "A rodada ativa os biomas do formato atual",
                    "Ao nascer na base: localize totem, ferro, ouro e loja",
                    "Construa para chegar a Ilha do Meio e ao Centro",
                },
                Starting = {
                    "Voce vai para uma base automaticamente",
                    "Ao nascer: pegue ferro e abra a loja",
                    "Pegue recurso antes de construir a primeira travessia",
                    "A Ilha do Meio e o Centro exigem construcao para travessia",
                    "A primeira meta e preparar ataque e defesa",
                },
                Active = {
                    "Pegue ferro e ouro no gerador da base",
                    "Abra a loja e compre blocos primeiro",
                    "Depois da ponte, pegue esmeralda e equipe o ataque",
                    "Construa para chegar a Ilha do Meio e pressionar outro bioma",
                },
                Spectating = {
                    "Sem respawn nesta rodada",
                    "Observe os times restantes",
                    "Espere o fim para voltar ao lobby",
                    "Use este tempo para ler o mapa e as rotas",
                },
            },
        },
        AdaptiveQueueText = {
            Current = "Fila: %d jogadores",
            Next = "Falta %d jogador(es) para iniciar",
            Format = "Formato previsto: %s",
            Active = "Rodada atual: %s",
        },
        StarterRecommendations = {
            BlockItemId = "wool_bundle",
            SwordItemId = "stone_sword",
            PickaxeItemId = "iron_pickaxe",
        },
        Messages = {
            ShopAccessDenied = "Acesso negado a loja.",
            PurchaseDenied = "Compra recusada.",
            PurchaseSuccess = "Compra concluida: %s",
            InsufficientFunds = "Saldo insuficiente.",
            DeliveryFailed = "Falha ao entregar item.",
            UpgradeDenied = "Upgrade recusado.",
            UpgradeMax = "Upgrade no maximo.",
            UpgradeInsufficient = "Recurso insuficiente para upgrade.",
            UpgradeSuccess = "Upgrade aplicado: %s",
            OverflowLobby = "A rodada atual ja esta completa. Aguarde no lobby: voce tem prioridade na proxima rodada.",
            VictoryAnnouncement = "%s venceu a rodada.",
            DrawAnnouncement = "Empate. Nenhum time sobreviveu.",
            TotemDownAnnouncement = "%s perdeu o totem. Agora sem respawn.",
        },
        Hints = {
            Lobby = "Veja o centro e espere a proxima rodada.",
            Countdown = "Prepare-se: voce vai nascer numa base ativa.",
            FirstBase = "Totem no centro, ferro na frente, loja ao lado e saidas marcadas para Meio e Centro.",
            NoResources = "Pegue ferro e ouro no gerador antes de comprar.",
            CanBuyBlocks = "Voce ja pode comprar blocos para defender ou avancar.",
            CanBuySword = "Voce ja pode comprar espada de pedra para a primeira troca.",
            NeedPickaxe = "Sem picareta voce nao quebra o totem inimigo.",
            CoreDestroyed = "Seu totem caiu. A proxima morte elimina voce da rodada.",
            RespawnActive = "Seu totem ainda esta ativo. Voce vai voltar em instantes.",
            Spectating = "Voce foi eliminado. Observe a rodada ate o retorno ao lobby.",
            LateJoin = "A rodada atual ja esta completa. Aguarde no lobby a proxima partida.",
            FirstIron = "Ferro compra blocos e abre sua defesa inicial.",
            FirstGold = "Ouro libera espada e picareta.",
            FirstEmerald = "Esmeralda cai no inventario e vale upgrades premium.",
            FirstPickaxe = "Picareta serve para quebrar blocos inimigos e acertar o totem.",
            FirstBridge = "Primeira ponte pronta. Agora avance para a Ilha do Meio.",
            FirstShopOpen = "A loja esta aberta. Pegue blocos antes de pensar em upgrade.",
            ReachMiddle = "Boa. A Ilha do Meio gera esmeralda para seu time.",
        },
        Results = {
            VictoryPrefix = "Vitoria:",
            DrawText = "Empate: nenhum time sobreviveu.",
            ReturnText = "Retorno ao lobby em instantes.",
        },
        HelpMessagesByState = {
            Lobby = "Leia a arena e espere a rodada",
            Waiting = "Leia a arena e espere a rodada",
            Starting = "Partida iniciando: pegue ferro assim que nascer",
            Active = "Pegue recurso, saia da base e pressione o totem inimigo",
            SuddenDeath = "Sem totem: sobreviva ate o fim",
            Spectating = "Voce foi eliminado; acompanhe a rodada",
            Ended = "Rodada encerrada; retorno ao lobby em instantes",
        },
        Theme = {
            BackgroundColor = Color3.fromRGB(13, 17, 24),
            PanelColor = Color3.fromRGB(23, 29, 40),
            AccentColor = Color3.fromRGB(91, 209, 247),
            TextColor = Color3.fromRGB(247, 250, 255),
            MutedTextColor = Color3.fromRGB(181, 194, 212),
            SuccessColor = Color3.fromRGB(102, 241, 167),
            WarningColor = Color3.fromRGB(250, 205, 84),
            DangerColor = Color3.fromRGB(255, 103, 103),
        },
    },

    Audio = {
        PickupSoundId = "rbxasset://sounds/electronicpingshort.wav",
        PurchaseSoundId = "rbxasset://sounds/button.wav",
        ErrorSoundId = "rbxasset://sounds/bass.wav",
        UpgradeSoundId = "rbxasset://sounds/electronicpingshort.wav",
        CoreHitSoundId = "rbxasset://sounds/snap.wav",
        CoreBreakSoundId = "rbxasset://sounds/uuhhh.mp3",
        VictorySoundId = "rbxasset://sounds/electronicpingshort.wav",
    },

    Analytics = {
        OnboardingFunnelName = "ftue_totem_loop",
        AllowedClientEvents = {
            ftue_open_help = true,
        },
    },

    Visual = {
        VisualQualityDefault = "Low",
        AllowStandardVisuals = true,
    },

    Compliance = {
        MaturityTarget = "Minimal",
        AllowRealNames = false,
        AllowLogos = false,
        AllowRecognizableLikeness = false,
        AllowRecognizableSlogans = false,
        AllowOffPlatformLinks = false,
        LicenseScope = "Only fictional team and biome labels are used; logos, voices, slogans, thumbnails, real names, and other protected assets remain blocked.",
        AssetRegisterPath = "docs/asset-register.md",
    },
}

return Config
