local VisualKit = {
    QualityTiers = {
        Low = {
            Technology = Enum.Technology.ShadowMap,
            UseSunRays = false,
            DecorativeLights = false,
            DecorativeParticles = false,
            GameplayBillboards = true,
            RouteBillboards = false,
            BillboardDistanceScale = 0.72,
            LightBrightnessScale = 0.68,
            LightRangeScale = 0.72,
            ParticleRateScale = 0.55,
            EnableIslandGlow = false,
            EnableLargeNeon = false,
        },
        Standard = {
            Technology = Enum.Technology.Future,
            UseSunRays = true,
            DecorativeLights = true,
            DecorativeParticles = true,
            GameplayBillboards = true,
            RouteBillboards = true,
            BillboardDistanceScale = 1,
            LightBrightnessScale = 1,
            LightRangeScale = 1,
            ParticleRateScale = 1,
            EnableIslandGlow = true,
            EnableLargeNeon = true,
        },
    },

    LightingPresets = {
        Low = {
            ClockTime = 14.45,
            Brightness = 1.65,
            ExposureCompensation = -0.28,
            Ambient = Color3.fromRGB(78, 83, 90),
            OutdoorAmbient = Color3.fromRGB(108, 112, 120),
            AtmosphereColor = Color3.fromRGB(186, 198, 208),
            AtmosphereDecay = Color3.fromRGB(102, 106, 114),
            AtmosphereDensity = 0.16,
            AtmosphereHaze = 0.58,
            AtmosphereGlare = 0.02,
            BloomIntensity = 0.015,
            BloomSize = 14,
            BloomThreshold = 2.9,
            Contrast = 0.09,
            Saturation = -0.01,
            TintColor = Color3.fromRGB(255, 255, 255),
            SunRaysIntensity = 0,
            SunRaysSpread = 0.64,
        },
        Standard = {
            ClockTime = 14.6,
            Brightness = 1.9,
            ExposureCompensation = -0.22,
            Ambient = Color3.fromRGB(74, 78, 84),
            OutdoorAmbient = Color3.fromRGB(104, 110, 116),
            AtmosphereColor = Color3.fromRGB(184, 198, 212),
            AtmosphereDecay = Color3.fromRGB(92, 98, 110),
            AtmosphereDensity = 0.2,
            AtmosphereHaze = 0.72,
            AtmosphereGlare = 0.04,
            BloomIntensity = 0.03,
            BloomSize = 18,
            BloomThreshold = 2.6,
            Contrast = 0.12,
            Saturation = -0.02,
            TintColor = Color3.fromRGB(255, 255, 255),
            SunRaysIntensity = 0.01,
            SunRaysSpread = 0.64,
        },
    },

    VfxBudget = {
        Low = {
            PermanentPointLights = 20,
            PermanentParticleEmitters = 8,
            AlwaysOnBillboards = 12,
            DoubleSurfaceSigns = 60,
        },
        Standard = {
            PermanentPointLights = 34,
            PermanentParticleEmitters = 20,
            AlwaysOnBillboards = 18,
            DoubleSurfaceSigns = 84,
        },
    },

    Global = {
        VoidColor = Color3.fromRGB(28, 40, 62),
        MetalDark = Color3.fromRGB(52, 46, 40),
        MetalMid = Color3.fromRGB(108, 96, 82),
        TextDark = Color3.fromRGB(16, 20, 28),
        TextLight = Color3.fromRGB(246, 250, 255),
        RouteMarker = Color3.fromRGB(111, 222, 255),
        Emerald = Color3.fromRGB(20, 232, 154),
        Iron = Color3.fromRGB(214, 222, 228),
        Gold = Color3.fromRGB(250, 202, 64),
    },

    Materials = {
        TerrainTop = Enum.Material.Ground,
        TerrainSide = Enum.Material.Rock,
        TerrainAccent = Enum.Material.Slate,
        Wood = Enum.Material.WoodPlanks,
        Banner = Enum.Material.SmoothPlastic,
        Beacon = Enum.Material.Neon,
    },

    BiomeSurfaceRules = {
        planicie = {
            TopMaterial = Enum.Material.Grass,
            MidMaterial = Enum.Material.Ground,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.WoodPlanks,
        },
        deserto = {
            TopMaterial = Enum.Material.Sand,
            MidMaterial = Enum.Material.Sandstone,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.Sandstone,
        },
        taiga = {
            TopMaterial = Enum.Material.Ground,
            MidMaterial = Enum.Material.Slate,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.WoodPlanks,
        },
        selva = {
            TopMaterial = Enum.Material.Grass,
            MidMaterial = Enum.Material.Ground,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.WoodPlanks,
        },
        neve = {
            TopMaterial = Enum.Material.Snow,
            MidMaterial = Enum.Material.Ice,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.Ice,
        },
        cogumelos = {
            TopMaterial = Enum.Material.Mud,
            MidMaterial = Enum.Material.Ground,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.WoodPlanks,
        },
        center = {
            TopMaterial = Enum.Material.Ground,
            MidMaterial = Enum.Material.Rock,
            SideMaterial = Enum.Material.Slate,
            AccentMaterial = Enum.Material.Rock,
        },
        lobby = {
            TopMaterial = Enum.Material.Ground,
            MidMaterial = Enum.Material.Rock,
            SideMaterial = Enum.Material.Rock,
            AccentMaterial = Enum.Material.WoodPlanks,
        },
    },

    Biomes = {
        planicie = {
            Primary = Color3.fromRGB(110, 176, 79),
            Secondary = Color3.fromRGB(127, 92, 60),
            Rim = Color3.fromRGB(77, 122, 67),
            Underside = Color3.fromRGB(72, 83, 64),
            Accent = Color3.fromRGB(190, 223, 140),
            Material = Enum.Material.Grass,
            DetailMaterial = Enum.Material.Ground,
            Landmark = "oak",
            PropStyle = "flowers",
        },
        deserto = {
            Primary = Color3.fromRGB(222, 189, 112),
            Secondary = Color3.fromRGB(188, 150, 92),
            Rim = Color3.fromRGB(171, 128, 74),
            Underside = Color3.fromRGB(105, 80, 56),
            Accent = Color3.fromRGB(239, 175, 88),
            Material = Enum.Material.Sand,
            DetailMaterial = Enum.Material.Sandstone,
            Landmark = "obelisk",
            PropStyle = "dunes",
        },
        taiga = {
            Primary = Color3.fromRGB(82, 118, 126),
            Secondary = Color3.fromRGB(76, 68, 60),
            Rim = Color3.fromRGB(58, 82, 90),
            Underside = Color3.fromRGB(42, 51, 60),
            Accent = Color3.fromRGB(150, 204, 215),
            Material = Enum.Material.Slate,
            DetailMaterial = Enum.Material.Ground,
            Landmark = "pine",
            PropStyle = "pines",
        },
        selva = {
            Primary = Color3.fromRGB(56, 140, 64),
            Secondary = Color3.fromRGB(87, 72, 44),
            Rim = Color3.fromRGB(38, 97, 48),
            Underside = Color3.fromRGB(38, 62, 42),
            Accent = Color3.fromRGB(148, 208, 98),
            Material = Enum.Material.Grass,
            DetailMaterial = Enum.Material.Ground,
            Landmark = "canopy",
            PropStyle = "jungle",
        },
        neve = {
            Primary = Color3.fromRGB(214, 230, 236),
            Secondary = Color3.fromRGB(164, 198, 214),
            Rim = Color3.fromRGB(162, 188, 200),
            Underside = Color3.fromRGB(95, 120, 137),
            Accent = Color3.fromRGB(168, 221, 235),
            Material = Enum.Material.Snow,
            DetailMaterial = Enum.Material.Ice,
            Landmark = "ice",
            PropStyle = "crystals",
        },
        cogumelos = {
            Primary = Color3.fromRGB(117, 76, 99),
            Secondary = Color3.fromRGB(172, 88, 108),
            Rim = Color3.fromRGB(92, 58, 79),
            Underside = Color3.fromRGB(63, 46, 66),
            Accent = Color3.fromRGB(220, 138, 158),
            Material = Enum.Material.Mud,
            DetailMaterial = Enum.Material.Ground,
            Landmark = "mushroom",
            PropStyle = "mushrooms",
        },
    },
}

return VisualKit
